//import { Inter } from "next/font/google";
import MainHeader from "@/components/header/main-header/main-header";
import "./globals.css";

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "News Archive Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div id="page">
          <MainHeader />

          {children}
        </div>
      </body>
    </html>
  );
}
